### PR TITLE
 Improve folder module

### PR DESCRIPTION
**Pull request by jdeniau**
I made a few improvements the two main changes in the code:

  * accept files with a `dash` in in by "camelCasing" the module name
  * accept files starting with a number by replacing the first number by the word
    * a small issue a see there is if you start with `12`, it will be replaced by `one2` but I personally don't have something like that for now ;)

I added tests to see that everything works fine. To achieve this, I needed to make `folder-module` usable as a function so it's pretty simple for now but in "test" env, you can use folder-module like an JS API instead of a node executable.

I automatically run [prettier](https://github.com/prettier/prettier) too on my codebase so the index.js file has been "prettified".

Thank you !

### CODE REVIEW

**Comment by Jamesernator** [comment]
I think enough people have dash file schemes to justify converting `foo-bar.js` into `fooBar` by default, however I'd rather not change valid identifiers like `foo_bar.js` into `fooBar` and especially not `_return.js` becoming `return`.

I don't think there's a strong case for converting numbers on the front of filenames into English words given that there's plenty of equally invalid characters that could be used anywhere in filenames that aren't JavaScript identifiers.

I think I'll make `folder-module` a function that takes a naming scheme function so that people can use their own custom schemes but the CLI will default to converting dashes to upper cast next character.

Something that I didn't really do anything about because it always assumed file names were valid identifiers was have any error handling, but now that it's possible to have both `foo-bar.js` and `fooBar.js` in a directory I think I'll just throw an error if an export were to be declared twice.

**Comment by jdeniau** [comment]
For the number thing, you are right, you can maybe just prefix with `_` if the first character is invalid.

**Comment by Jamesernator** [comment]
I finally got around to it and pushed a `2.x.x` folder-module out that allows for `-` in the filename, it basically replaces `-x` with `-X` so `make-soup.js` will become `makeSoup` as the exports.

Unlike slugify `-soup-recipe.js` will become `SoupRecipe` as the export, whereas slugify would've made it `soupRecipe` still.

The new folder module will throw if there's any files that'd lead to an invalid variable name in the exports, but it also ignores files that have no extension or start with either `.` or `#` so you can use those as "private" modules which won't be exported in the folder module.

**Comment by jdeniau** [comment]
Great !

Just for the record, I finally do not use you project (my project was much more complex, so I found another solution).

I will close this PR but feel free to take anything you want in it, particularly the tests section may help other if they need to improve folder-modules.

Thanks anyway !

**Pull request closed without merging**
